package mapCreator;

import baha.MazeFactory;
import baha.component.Door;
import baha.component.Room;
import items.Key;

import java.util.HashMap;
import java.util.List;

public class Map1DoorsCreator {
    public static void createMap1Doors(List<Room> rooms, MazeFactory mazeGame, HashMap<String, Key> keys){
        Door d0 = mazeGame.MakeDoor(rooms.get(0), rooms.get(3));
        rooms.get(0).setMapSites(d0, 0);
        rooms.get(3).setMapSites(d0, 2);
        d0.setNeededKeyName("the demon king room key");
        d0.lock(keys.get("the demon king room key"));
        Door d1 = mazeGame.MakeDoor(rooms.get(3), rooms.get(7));
        rooms.get(3).setMapSites(d1, 0);
        rooms.get(7).setMapSites(d1, 2);
        Door d2 = mazeGame.MakeDoor(rooms.get(7), rooms.get(2));
        rooms.get(7).setMapSites(d2, 0);
        rooms.get(2).setMapSites(d2, 2);
        Door d3 = mazeGame.MakeDoor(rooms.get(2), rooms.get(10));
        rooms.get(2).setMapSites(d3, 0);
        rooms.get(10).setMapSites(d3, 2);
        Door d4 = mazeGame.MakeDoor(rooms.get(7), rooms.get(15));
        rooms.get(7).setMapSites(d4, 1);
        rooms.get(15).setMapSites(d4, 3);
        d4.setNeededKeyName("the human king room key");
        d4.lock(keys.get("the human king room key"));
        Door d5 = mazeGame.MakeDoor(rooms.get(15), rooms.get(16));
        rooms.get(15).setMapSites(d5, 0);
        rooms.get(16).setMapSites(d5, 2);
        Door d6 = mazeGame.MakeDoor(rooms.get(16), rooms.get(31));
        rooms.get(16).setMapSites(d6, 1);
        rooms.get(31).setMapSites(d6, 3);
        d6.setNeededKeyName("the fairy queen room key");
        d6.lock(keys.get("the fairy queen room key"));
        Door d7 = mazeGame.MakeDoor(rooms.get(31), rooms.get(49));
        rooms.get(31).setMapSites(d7, 1);
        rooms.get(49).setMapSites(d7, 3);
        Door d8 = mazeGame.MakeDoor(rooms.get(49), rooms.get(40));
        rooms.get(49).setMapSites(d8, 0);
        rooms.get(40).setMapSites(d8, 1);
        Door d9 = mazeGame.MakeDoor(rooms.get(40), rooms.get(25));
        rooms.get(40).setMapSites(d9, 3);
        rooms.get(25).setMapSites(d9, 1);
        d9.setNeededKeyName("the mermaid queen room key");
        d9.lock(keys.get("the mermaid queen room key"));
        Door d10 = mazeGame.MakeDoor(rooms.get(25), rooms.get(19));
        rooms.get(25).setMapSites(d10, 0);
        rooms.get(19).setMapSites(d10, 2);
        d10.setNeededKeyName("the jungle nymph room key");
        d10.lock(keys.get("the jungle nymph room key"));


        Door d11 = mazeGame.MakeDoor(rooms.get(20), rooms.get(9));
        rooms.get(20).setMapSites(d11, 0);
        rooms.get(9).setMapSites(d11, 2);
        d11.setNeededKeyName("the ghost whale room key");
        d11.lock(keys.get("the ghost whale room key"));
        Door d12 = mazeGame.MakeDoor(rooms.get(9), rooms.get(24));
        rooms.get(9).setMapSites(d12, 0);
        rooms.get(24).setMapSites(d12, 2);
        Door d13 = mazeGame.MakeDoor(rooms.get(9), rooms.get(42));
        rooms.get(9).setMapSites(d13, 1);
        rooms.get(42).setMapSites(d13, 3);
        Door d14 = mazeGame.MakeDoor(rooms.get(42), rooms.get(45));
        rooms.get(42).setMapSites(d14, 1);
        rooms.get(45).setMapSites(d14, 3);
        d14.setNeededKeyName("demon of wrath room key");
        d14.lock(keys.get("demon of wrath room key"));
        Door d15 = mazeGame.MakeDoor(rooms.get(45), rooms.get(46));
        rooms.get(45).setMapSites(d15, 1);
        rooms.get(46).setMapSites(d15, 3);
        Door d16 = mazeGame.MakeDoor(rooms.get(46), rooms.get(38));
        rooms.get(46).setMapSites(d16, 1);
        rooms.get(38).setMapSites(d16, 3);
        d16.setNeededKeyName("the prince of demons room key");
        d16.lock(keys.get("the prince of demons room key"));
        Door d17 = mazeGame.MakeDoor(rooms.get(38), rooms.get(8));
        rooms.get(38).setMapSites(d17, 1);
        rooms.get(8).setMapSites(d17, 3);
        d17.setNeededKeyName("the sea dragon room key");
        d17.lock(keys.get("the sea dragon room key"));
        Door d18 = mazeGame.MakeDoor(rooms.get(8), rooms.get(41));
        rooms.get(8).setMapSites(d18, 0);
        rooms.get(41).setMapSites(d18, 1);
        Door d19 = mazeGame.MakeDoor(rooms.get(41), rooms.get(34));
        rooms.get(41).setMapSites(d19, 2);
        rooms.get(34).setMapSites(d19, 0);
        Door d20 = mazeGame.MakeDoor(rooms.get(41), rooms.get(5));
        rooms.get(41).setMapSites(d20, 0);
        rooms.get(5).setMapSites(d20, 2);
        d20.setNeededKeyName("the ice demon room key");
        d20.lock(keys.get("the ice demon room key"));


        Door d21 = mazeGame.MakeDoor(rooms.get(23), rooms.get(11));
        rooms.get(23).setMapSites(d21, 0);
        rooms.get(11).setMapSites(d21, 2);
        Door d22 = mazeGame.MakeDoor(rooms.get(11), rooms.get(43));
        rooms.get(11).setMapSites(d22, 1);
        rooms.get(43).setMapSites(d22, 3);
        Door d23 = mazeGame.MakeDoor(rooms.get(43), rooms.get(36));
        rooms.get(43).setMapSites(d23, 1);
        rooms.get(36).setMapSites(d23, 3);
        Door d24 = mazeGame.MakeDoor(rooms.get(36), rooms.get(18));
        rooms.get(36).setMapSites(d24, 1);
        rooms.get(18).setMapSites(d24, 3);
        d24.setNeededKeyName("the lightning fairy room key");
        d24.lock(keys.get("the lightning fairy room key"));
        Door d25 = mazeGame.MakeDoor(rooms.get(36), rooms.get(27));
        rooms.get(36).setMapSites(d25, 0);
        rooms.get(27).setMapSites(d25, 2);
        d25.setNeededKeyName("the goblins king room key");
        d25.lock(keys.get("the goblins king room key"));
        Door d26 = mazeGame.MakeDoor(rooms.get(27), rooms.get(28));
        rooms.get(27).setMapSites(d26, 1);
        rooms.get(28).setMapSites(d26, 3);
        d26.setNeededKeyName("the slime room key");
        d26.lock(keys.get("the slime room key"));
        Door d27 = mazeGame.MakeDoor(rooms.get(27), rooms.get(14));
        rooms.get(27).setMapSites(d27, 3);
        rooms.get(14).setMapSites(d27, 1);
        Door d28 = mazeGame.MakeDoor(rooms.get(14), rooms.get(47));
        rooms.get(14).setMapSites(d28, 2);
        rooms.get(47).setMapSites(d28, 0);
        d28.setNeededKeyName("the wargs king room key");
        d28.lock(keys.get("the wargs king room key"));
        Door d29 = mazeGame.MakeDoor(rooms.get(14), rooms.get(33));
        rooms.get(14).setMapSites(d29, 0);
        rooms.get(33).setMapSites(d29, 2);
        d29.setNeededKeyName("the mumakil room key");
        d29.lock(keys.get("the mumakil room key"));
        Door d30 = mazeGame.MakeDoor(rooms.get(33), rooms.get(6));
        rooms.get(33).setMapSites(d30, 0);
        rooms.get(6).setMapSites(d30, 2);
        d30.setNeededKeyName("the trolls king room key");
        d30.lock(keys.get("the trolls king room key"));


        Door d31 = mazeGame.MakeDoor(rooms.get(1), rooms.get(13));
        rooms.get(1).setMapSites(d31, 0);
        rooms.get(13).setMapSites(d31, 2);
        Door d32 = mazeGame.MakeDoor(rooms.get(13), rooms.get(17));
        rooms.get(13).setMapSites(d32, 1);
        rooms.get(17).setMapSites(d32, 3);
        Door d33 = mazeGame.MakeDoor(rooms.get(17), rooms.get(21));
        rooms.get(17).setMapSites(d33, 1);
        rooms.get(21).setMapSites(d33, 3);
        d33.setNeededKeyName("the eagles king key");
        d33.lock(keys.get("the eagles king key"));
        Door d34 = mazeGame.MakeDoor(rooms.get(21), rooms.get(22));
        rooms.get(21).setMapSites(d34, 1);
        rooms.get(22).setMapSites(d34, 3);
        Door d35 = mazeGame.MakeDoor(rooms.get(22), rooms.get(26));
        rooms.get(22).setMapSites(d35, 1);
        rooms.get(26).setMapSites(d35, 3);
        d35.setNeededKeyName("the wizards king room key");
        d35.lock(keys.get("the wizards king room key"));
        Door d36 = mazeGame.MakeDoor(rooms.get(21), rooms.get(35));
        rooms.get(21).setMapSites(d36, 0);
        rooms.get(35).setMapSites(d36, 1);
        d36.setNeededKeyName("the fire dragon room key");
        d36.lock(keys.get("the fire dragon room key"));
        Door d37 = mazeGame.MakeDoor(rooms.get(35), rooms.get(32));
        rooms.get(35).setMapSites(d37, 3);
        rooms.get(32).setMapSites(d37, 1);
        Door d38 = mazeGame.MakeDoor(rooms.get(32), rooms.get(37));
        rooms.get(32).setMapSites(d38, 0);
        rooms.get(37).setMapSites(d38, 2);
        d38.setNeededKeyName("the gaints room key");
        d38.lock(keys.get("the gaints room key"));
        Door d39 = mazeGame.MakeDoor(rooms.get(32), rooms.get(30));
        rooms.get(32).setMapSites(d39, 3);
        rooms.get(30).setMapSites(d39, 1);
        Door d40 = mazeGame.MakeDoor(rooms.get(30), rooms.get(29));
        rooms.get(30).setMapSites(d40, 2);
        rooms.get(29).setMapSites(d40, 0);
        d40.setNeededKeyName("the sage room key");
        d40.lock(keys.get("the sage room key"));
        Door d41 = mazeGame.MakeDoor(rooms.get(30), rooms.get(48));
        rooms.get(30).setMapSites(d41, 0);
        rooms.get(48).setMapSites(d41, 2);
        Door d42 = mazeGame.MakeDoor(rooms.get(48), rooms.get(12));
        rooms.get(48).setMapSites(d42, 0);
        rooms.get(12).setMapSites(d42, 2);
        d42.setNeededKeyName("the stray dogs room key");
        d42.lock(keys.get("the stray dogs room key"));


        Door d43 = mazeGame.MakeDoor(rooms.get(40), rooms.get(8));
        rooms.get(40).setMapSites(d43, 0);
        rooms.get(8).setMapSites(d43, 1);
        Door d44 = mazeGame.MakeDoor(rooms.get(33), rooms.get(48));
        rooms.get(33).setMapSites(d44, 1);
        rooms.get(48).setMapSites(d44, 1);
    }
}
